-- Enable pgvector extension if not already enabled (optional but good practice)
CREATE EXTENSION IF NOT EXISTS vector;

-- Table for flashcards
CREATE TABLE IF NOT EXISTS flashcards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type TEXT NOT NULL CHECK(type IN ('front_back', 'cloze')), -- Keep original type
    exercise_type TEXT CHECK(exercise_type IN ('front_back', 'mcq', 'cloze')) DEFAULT 'front_back', -- Relevant for MCQ
    front TEXT NULL,        -- Front content (e.g., English word/prompt)
    back TEXT NULL,         -- Back content (e.g., Chinese word/answer)
    cloze_text TEXT NULL,
    source_url TEXT,
    source_highlight TEXT,  -- Original highlighted text (can be english word lowercased)
    source_language TEXT NULL,
    target_language TEXT NULL,
    context TEXT NULL,      -- Full original definition can go here
    tags TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    exercise_data TEXT NULL, -- Relevant for storing MCQ options/answer

    -- FSRS related fields
    due TIMESTAMPTZ,
    stability REAL DEFAULT 0,
    difficulty REAL DEFAULT 0,
    elapsed_days INTEGER DEFAULT 0,
    scheduled_days INTEGER DEFAULT 0,
    reps INTEGER DEFAULT 0,
    lapses INTEGER DEFAULT 0,
    state INTEGER DEFAULT 0,
    last_review TIMESTAMPTZ NULL,

    -- Ensure unique basic word pairs for ON CONFLICT clause (can be adjusted later if needed)
    UNIQUE(source_language, target_language, front, back)
);

-- Optional: Index for exercise type (Relevant)
CREATE INDEX IF NOT EXISTS idx_flashcards_exercise_type ON flashcards(exercise_type);

-- Optional: Index for faster flashcard lookups by due date (Relevant for SRS)
CREATE INDEX IF NOT EXISTS idx_flashcards_due ON flashcards(due);

-- Table for storing processed webpage content (markdown) and optional embeddings
CREATE TABLE IF NOT EXISTS webpages (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    url TEXT NOT NULL,
    title TEXT NULL,
    visited_at TIMESTAMP NOT NULL, -- Use the visit time from browser history or processing time
    markdown_content TEXT NULL,     -- Store the markdown from the Reader model
    embedding TEXT NULL,             -- Store embedding vector as JSON string or use vector type later
    embedding_model TEXT NULL,       -- Model identifier (e.g., 'nomic-embed-text:latest')
    embedding_dim INTEGER NULL,      -- Dimension of the stored embedding (e.g., 768)
    UNIQUE(url, visited_at)          -- Prevent duplicate entries for the exact same visit/processing event
);

-- Optional: Index for faster history lookup by URL (on webpages table)
CREATE INDEX IF NOT EXISTS idx_webpages_url ON webpages(url);
